/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RegularsRouteImport } from './routes/regulars'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'
import { Route as OnboardingAccountRouteImport } from './routes/onboarding.account'
import { Route as OnboardingValueRouteImport } from './routes/onboarding.value'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts.$receiptId'
import { Route as ReportsWeeklyRouteImport } from './routes/reports.weekly'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as ScanResultsRouteImport } from './routes/scan.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularsRoute = RegularsRouteImport.update({
  id: '/regulars',
  path: '/regulars',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAccountRoute = OnboardingAccountRouteImport.update({
  id: '/onboarding/account',
  path: '/onboarding/account',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingValueRoute = OnboardingValueRouteImport.update({
  id: '/onboarding/value',
  path: '/onboarding/value',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsWeeklyRoute = ReportsWeeklyRouteImport.update({
  id: '/reports/weekly',
  path: '/reports/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanRoute,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ScanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/regulars': typeof RegularsRoute
  '/scan': typeof ScanRouteWithChildren
  '/search': typeof SearchRoute
  '/streak': typeof StreakRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/value': typeof OnboardingValueRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/reports/weekly': typeof ReportsWeeklyRoute
  '/scan/results': typeof ScanResultsRoute
  '/deals/': typeof DealsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/regulars': typeof RegularsRoute
  '/search': typeof SearchRoute
  '/streak': typeof StreakRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/value': typeof OnboardingValueRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/reports/weekly': typeof ReportsWeeklyRoute
  '/scan/results': typeof ScanResultsRoute
  '/deals': typeof DealsIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/scan': typeof ScanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/regulars': typeof RegularsRoute
  '/scan': typeof ScanRouteWithChildren
  '/search': typeof SearchRoute
  '/streak': typeof StreakRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/value': typeof OnboardingValueRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/reports/weekly': typeof ReportsWeeklyRoute
  '/scan/results': typeof ScanResultsRoute
  '/deals/': typeof DealsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/regulars'
    | '/scan'
    | '/search'
    | '/streak'
    | '/deals/$dealId'
    | '/onboarding/account'
    | '/onboarding/value'
    | '/receipts/$receiptId'
    | '/reports/weekly'
    | '/scan/results'
    | '/deals/'
    | '/receipts/'
    | '/scan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/regulars'
    | '/search'
    | '/streak'
    | '/deals/$dealId'
    | '/onboarding/account'
    | '/onboarding/value'
    | '/receipts/$receiptId'
    | '/reports/weekly'
    | '/scan/results'
    | '/deals'
    | '/receipts'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/regulars'
    | '/scan'
    | '/search'
    | '/streak'
    | '/deals/$dealId'
    | '/onboarding/account'
    | '/onboarding/value'
    | '/receipts/$receiptId'
    | '/reports/weekly'
    | '/scan/results'
    | '/deals/'
    | '/receipts/'
    | '/scan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  RegularsRoute: typeof RegularsRoute
  ScanRoute: typeof ScanRouteWithChildren
  SearchRoute: typeof SearchRoute
  StreakRoute: typeof StreakRoute
  DealsDealIdRoute: typeof DealsDealIdRoute
  OnboardingAccountRoute: typeof OnboardingAccountRoute
  OnboardingValueRoute: typeof OnboardingValueRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
  ReportsWeeklyRoute: typeof ReportsWeeklyRoute
  DealsIndexRoute: typeof DealsIndexRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulars': {
      id: '/regulars'
      path: '/regulars'
      fullPath: '/regulars'
      preLoaderRoute: typeof RegularsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/account': {
      id: '/onboarding/account'
      path: '/onboarding/account'
      fullPath: '/onboarding/account'
      preLoaderRoute: typeof OnboardingAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/value': {
      id: '/onboarding/value'
      path: '/onboarding/value'
      fullPath: '/onboarding/value'
      preLoaderRoute: typeof OnboardingValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$receiptId': {
      id: '/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/weekly': {
      id: '/reports/weekly'
      path: '/reports/weekly'
      fullPath: '/reports/weekly'
      preLoaderRoute: typeof ReportsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/results': {
      id: '/scan/results'
      path: '/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof ScanRoute
    }
  }
}

interface ScanRouteChildren {
  ScanResultsRoute: typeof ScanResultsRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanResultsRoute: ScanResultsRoute,
  ScanIndexRoute: ScanIndexRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  RegularsRoute: RegularsRoute,
  ScanRoute: ScanRouteWithChildren,
  SearchRoute: SearchRoute,
  StreakRoute: StreakRoute,
  DealsDealIdRoute: DealsDealIdRoute,
  OnboardingAccountRoute: OnboardingAccountRoute,
  OnboardingValueRoute: OnboardingValueRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
  ReportsWeeklyRoute: ReportsWeeklyRoute,
  DealsIndexRoute: DealsIndexRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
