/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OnboardingAccountRouteImport } from './routes/onboarding.account'
import { Route as OnboardingValueRouteImport } from './routes/onboarding.value'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAccountRoute = OnboardingAccountRouteImport.update({
  id: '/onboarding/account',
  path: '/onboarding/account',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingValueRoute = OnboardingValueRouteImport.update({
  id: '/onboarding/value',
  path: '/onboarding/value',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/value': typeof OnboardingValueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/value': typeof OnboardingValueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/value': typeof OnboardingValueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/onboarding/account' | '/onboarding/value'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/onboarding/account' | '/onboarding/value'
  id: '__root__' | '/' | '/home' | '/onboarding/account' | '/onboarding/value'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  OnboardingAccountRoute: typeof OnboardingAccountRoute
  OnboardingValueRoute: typeof OnboardingValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/account': {
      id: '/onboarding/account'
      path: '/onboarding/account'
      fullPath: '/onboarding/account'
      preLoaderRoute: typeof OnboardingAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/value': {
      id: '/onboarding/value'
      path: '/onboarding/value'
      fullPath: '/onboarding/value'
      preLoaderRoute: typeof OnboardingValueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  OnboardingAccountRoute: OnboardingAccountRoute,
  OnboardingValueRoute: OnboardingValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
